Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;

namespace SistemaVendas.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListaClientes = new ClienteModel().ListaTodosClientes();
            return View();
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            if (id!= null)
            {
                //carrega registro do cliente na viewbag
                ViewBag.Cliente = new ClienteModel().RetornarClientes(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(ClienteModel cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }
            
        public IActionResult ExcluirCliente(int id)
        {
            new ClienteModel().Excluir(id);
            return View();
        }

    }
}

Views/Cliente/Cadastro.cshtml
@model ClienteModel

<h2>Cadastro de Clientes</h2>

<br />

<form asp-controller="Cliente" asp-action="Cadastro">
    <input type="hidden" asp-for="Id" value="@try { @ViewBag.Cliente.Id } catch { } " />
    <div class="form-group">
        <label>Nome</label>
        <input asp-for="Nome" type="text" class="form-control" value="@try { @ViewBag.Cliente.Nome } catch { } " />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>CPF/CNPJ</label>
        <input asp-for="CPF" type="text" class="form-control" value="@try { @ViewBag.Cliente.CPF } catch { } " />
        <span asp-validation-for="CPF" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Email</label>
        <input asp-for="Email" type="text" class="form-control" value="@try { @ViewBag.Cliente.Email } catch { } " />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Lista de Clientes</button>

<script>
    function Voltar() {
        window.location.href = '../../Cliente/Index';
    }
</script>

Views/Cliente/Excluir.cshtml
<h2>Excluir Cliente</h2>

<h3>Deseja realmente excluir o cliente selecionado?</h3>
<br />
<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>
    function Sim()
    {
        window.location.href = '../../Cliente/ExcluirCliente/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao()
    {
        window.location.href = '../../Cliente/Index';
    }

</script>

Views/Cliente/ExcluirCliente.cshtml
<h2>Cliente excluido com sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">OK</button>

<script>
    function Voltar()
    {
        window.location.href = '../../Cliente/Index';
    }
</script>

Views/Cliente/Index.cshtml
<h3>Lista de Clientes</h3>

<table class="table table-bordered">

    <thead>
        <tr>
            <td>#</td>
            <td>#</td>
            <td>Id</td>
            <td>Nome</td>
            <td>Cpf</td>
            <td>Email</td>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var item in (List<ClienteModel>)ViewBag.ListaClientes)
            {
                <tr>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
                    <td>@item.Id</td>
                    <td>@item.Nome</td>
                    <td>@item.CPF</td>
                    <td>@item.Email</td>
                </tr>

            }
        }
    </tbody>

</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar</button>

<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Menu</button>

<script>
    function Voltar() {
        window.location.href = "../Home/Menu"
    }
</script>

<script>
    function Cadastrar() {
        window.location.href = "../Cliente/Cadastro";
    }

    function Editar(id) {
        window.location.href = "../Cliente/Cadastro/" + id;
    }

    function Excluir(id) {
        window.location.href = "../Cliente/Excluir/" + id;
    }
</script>