Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;

namespace SistemaVendas.Controllers
{
    public class ProdutoController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListaProduto = new ProdutoModel().ListaTodosProdutos();
            return View();
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            if (id!= null)
            {
                //carrega registro do Vendedor na viewbag
                ViewBag.Produto = new ProdutoModel().RetornarProdutos(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(ProdutoModel produto)
        {
            if (ModelState.IsValid)
            {
                produto.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }

        public IActionResult ExcluirVendedor(int id)
        {
            new ProdutoModel().Excluir(id);
            return View();
        }

    }
}

Views/Produto/Cadastro.cshtml
@model ProdutoModel

<h2>Cadastro de Produtos</h2>

<br />

<form asp-controller="Produto" asp-action="Cadastro">
    <input type="hidden" asp-for="Id" value="@try { @ViewBag.Produto.Id } catch { } " />
    <div class="form-group">
        <label>Nome</label>
        <input asp-for="Nome" type="text" class="form-control" value="@try { @ViewBag.Produto.Nome } catch { } " />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Descrição</label>
        @{
            var vDescricao = "";

            try
            {
                vDescricao = ViewBag.Produto.Descricao;
            }
            catch { }
                       
        }

        @Html.TextArea("Descricao", vDescricao, new { @class="form-control" })

        @*<input asp-for="Descricao" type="text" class="form-control" value="@try { @ViewBag.Produto.Descricao } catch { } " />*@
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Preço Unitário</label>
        <input asp-for="Preco_Unitario" type="text" class="form-control" value="@try { @ViewBag.Produto.Preco_Unitario } catch { } " />
        <span asp-validation-for="Preco_Unitario" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Qtde. Estoque</label>
        <input asp-for="Quantidade_Estoque" type="text" class="form-control" value="@try { @ViewBag.Produto.Quantidade_Estoque } catch { } " />
        <span asp-validation-for="Quantidade_Estoque" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Unidade Medida</label>
        @*<input asp-for="Unidade_Medida" type="text" class="form-control" value="@try { @ViewBag.Produto.Unidade_Medida } catch { } " />*@
        
        @{ 
            var vUnidadeMedida = "";
            try
            {
                vUnidadeMedida = ViewBag.Produto.Unidade_Medida;
            }
            catch { }
        

        }

        <select asp-for="Unidade_Medida" class="form-control">
            @{
                if (vUnidadeMedida != "")
                {
            <option value="@vUnidadeMedida" selected>@vUnidadeMedida</option>
                }
            }

            <option value="un">un</option>
            <option value="cm">cm</option>
            <option value="mt">mt</option>
            <option value="ml">ml</option>
            <option value="kg">kg</option>
        </select>
        <span asp-validation-for="Unidade_Medida" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Foto</label>
        @try
        {
           <img src="@try { @ViewBag.Produto.Link_Foto } catch { }" width="150" height="150" />
        }
        catch (Exception)
        {

            throw;
        }

        <input asp-for="Link_Foto" type="text" class="form-control" value="@try { @ViewBag.Produto.Link_Foto } catch { } " />
        <span asp-validation-for="Link_Foto" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>
<br />
<button type="submit" class="btn btn-block btn-primary" onclick="Voltar()">Listagem de Produtos</button>

<script>
    function Voltar() {
        window.location.href = '../../produto/index';
    }
</script>

Views/Produto/Excluir.cshtml
<h2>Excluir Produto</h2>

<h3>Deseja realmente excluir o produto selecionado?</h3>
<br />
<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>
    function Sim()
    {
        window.location.href = '../../Produto/ExcluirProduto/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao()
    {
        window.location.href = '../../Produto/Index';
    }

</script>

Views/Produto/ExcluirProduto.cshtml
<h2>Produto excluido com sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">OK</button>

<script>
    function Voltar()
    {
        window.location.href = '../../Produto/Index';
    }
</script>

Views/Produto/Index.cshtml
<h3>Lista de Produtos</h3>

<table class="table table-bordered">

    <thead>
        <tr>
            <td>#</td>
            <td>#</td>
            <td>Id</td>
            <td>Nome</td>
            <td>Descricao</td>
            <td>Preco Unitario</td>
            <td>Quantidade Estoque</td>
            <td>Unidade Medica</td>
            <td>Foto</td>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var item in (List<ProdutoModel>)ViewBag.ListaProduto)
            {
                <tr>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
                    <td>@item.Id</td>
                    <td>@item.Nome</td>
                    <td>@item.Descricao</td>
                    <td>@item.Preco_Unitario</td>
                    <td>@item.Quantidade_Estoque</td>
                    <td>@item.Unidade_Medida</td>
                    <td><img src="@item.Link_Foto" width="150" heigth="150" /></td>

                </tr>

            }
        }
    </tbody>

</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar</button>

<script>
    function Cadastrar() {
        window.location.href = "../Produto/Cadastro";
    }

    function Editar(id) {
        window.location.href = "../Produto/Cadastro/" + id;
    }

    function Excluir(id) {
        window.location.href = "../Produto/Excluir/" + id;
    }
</script>

<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Menu</button>

<script>
    function Voltar() {
        window.location.href = "../Home/Menu"
    }
</script>