Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;

namespace SistemaVendas.Controllers
{
    public class RelatorioController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Vendas()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Vendas(RelatorioModel relatorio)
        {
            if (relatorio.DataIni.Year == 1)
            {
                ViewBag.ListaVendas = new VendaModel().ListagemVendas();
            }
            else
            {
                string DataIni = relatorio.DataIni.ToString("yyy/MM/dd");
                string DataFim = relatorio.DataFim.ToString("yyy/MM/dd");
                ViewBag.ListaVendas = new VendaModel().ListagemVendas(DataIni, DataFim);
            }
           
            return View();
        }

        public IActionResult Grafico()
        {
            List<GraficoProdutos> lista = new GraficoProdutos().RetornaGrafico();
            string valores = "";
            string labels = "";
            string cores = "";

            var random = new Random();
            //percorre lista de itens para compor o grafico

            for (int i = 0; i < lista.Count; i++)
            {
                valores += lista[i].QtdeVendido.ToString() + ",";
                labels += "'" + lista[i].DescricaoProduto.ToString() + "',";

                //escolher aleatoriamente as cores para compor o grafico pizza
                cores += "'" + String.Format("#{0:X6}", random.Next(0x1000000)) + "',";

            }

            ViewBag.Valores = valores;
            ViewBag.Labels = labels;
            ViewBag.Cores = cores;

            return View();
        }
    }
}

Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;
using Microsoft.AspNetCore.Http;

namespace SistemaVendas.Controllers
{
    public class VendaController : Controller
    {
        private IHttpContextAccessor httpContext;

        //recebe o contexto http via injeção de dependencia
        public VendaController(IHttpContextAccessor HttpContextAccessor)
        {
            httpContext = HttpContextAccessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.ListaVendas = new VendaModel().ListagemVendas();
            return View();
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            CarregarDados();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(VendaModel venda)
        {
            venda.Vendedor_Id = httpContext.HttpContext.Session.GetString("IdUsuarioLogado");
            venda.Inserir();
            CarregarDados();
            return View();
        }

        public void CarregarDados()
        {
            ViewBag.ListaClientes = new VendaModel().RetornaListaClientes();
            ViewBag.ListaVendedor = new VendaModel().RetornaListaVendedor();
            ViewBag.ListaProdutos = new VendaModel().RetornaListaProdutos();
        }

    }
}

Views/Relatorio/Grafico.cshtml
<h2>Graficos</h2>


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.bundle.min.js"></script>




<div id="canvas-holder" style="width:40%">
    <canvas id="chart-area"></canvas>
</div>

<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [@Html.Raw(ViewBag.Valores)],
                backgroundColor: [@Html.Raw(ViewBag.Cores)],
                label: 'Dataset 1'
            }],
            labels: [@Html.Raw(ViewBag.Labels)]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };


</script>

Views/Relatorio/Index.cshtml
<h2>Relatórios do Sistema</h2>

<button class="btn btn-block btn-primary" type="button" onclick="Reletorio('Vendas')">Vendas por Período</button>
<button class="btn btn-block btn-warning" type="button" onclick="Reletorio('Vendas')">Vendas por Produto</button>
<button class="btn btn-block btn-success" type="button" onclick="Reletorio('Vendas')">Vendas por Clientes</button>
<button class="btn btn-block btn-lg" type="button" onclick="Reletorio('Grafico')">Graficos</button>

<script>
    function Reletorio(action) {
        window.location.href = "../Relatorio/" + action;
    }
</script>


<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Menu</button>

<script>
    function Voltar() {
        window.location.href = "../Home/Menu"
    }
</script>

Views/Relatorio/Vendas.cshtml
@model RelatorioModel
<h2>Vendas Por Período</h2>

<br />

<form asp-controller="Relatorio" asp-action="Vendas">
    <div class="form-group">
        <label>Período</label>
        <input asp-for="DataIni" type="date" class="form-control" />
    </div>

    <div class="form-group">
        <input asp-for="DataFim" type="date" class="form-control" />
    </div>

    <button type="submit" class="btn btn-block btn-success">Pesquisar </button>
</form>

<br />
<table class="table table-bordered">

    <thead>
        <tr>

            <td>Id</td>
            <td>Data</td>
            <td>Vendedor</td>
            <td>Cliente</td>
            <td>Total</td>
        </tr>
    </thead>

    <tbody>
        @{
            try
            {
                foreach (var item in (List<VendaModel>)ViewBag.ListaVendas)
                {
                <tr>

                    <td>@item.Id</td>
                    <td>@item.Data</td>
                    <td>@item.Vendedor_Id</td>
                    <td>@item.Cliente_Id</td>
                    <td>@item.Total</td>
                </tr>

                    }

                }
                catch
                {


                }
            }

    </tbody>

</table>

<script>
    function Cadastrar() {
        window.location.href = "../Venda/Registrar";
    }


</script>


<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Lista de Clientes</button>

<script>
    function Voltar() {
        window.location.href = '../../Cliente/Index';
    }
</script>

Views/Relatorio/VendasProdutos.cshtml
@model RelatorioModel
<h2>Vendas Por Produto</h2>

<br />

<form asp-controller="Relatorio" asp-action="Vendas">
    <div class="form-group">
        <label>Período</label>

    </div>

    <button type="submit" class="btn btn-block btn-success">Pesquisar </button>
</form>

<br />
<table class="table table-bordered">

    <thead>
        <tr>

            <td>Id</td>
            <td>Data</td>
            <td>Vendedor</td>
            <td>Cliente</td>
            <td>Total</td>
        </tr>
    </thead>

    <tbody>
        @{
            try
            {
                foreach (var item in (List<VendaModel>)ViewBag.ListaVendas)
                {
                <tr>

                    <td>@item.Id</td>
                    <td>@item.Data</td>
                    <td>@item.Vendedor_Id</td>
                    <td>@item.Cliente_Id</td>
                    <td>@item.Total</td>
                </tr>

                    }

                }
                catch
                {


                }
            }

    </tbody>

</table>

<script>
    function Cadastrar() {
        window.location.href = "../Venda/Registrar";
    }


</script>


<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Lista de Clientes</button>

<script>
    function Voltar() {
        window.location.href = '../../Cliente/Index';
    }
</script>