Controllers/VendedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;

namespace SistemaVendas.Controllers
{
    public class VendedorController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListaVendedores = new VendedorModel().ListaTodosVendedores();
            return View();
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            if (id!= null)
            {
                //carrega registro do Vendedor na viewbag
                ViewBag.Vendedor = new VendedorModel().RetornarVendedor(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(VendedorModel vendedor)
        {
            if (ModelState.IsValid)
            {
                vendedor.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }

        public IActionResult ExcluirVendedor(int id)
        {
            new VendedorModel().Excluir(id);
            return View();
        }

    }
}

Views/Vendedor/Cadastro.cshtml
@model VendedorModel

<h2>Cadastro de Vendedor</h2>

<br />

<form asp-controller="Vendedor" asp-action="Cadastro">
    <input type="hidden" asp-for="Id" value="@try { @ViewBag.Vendedor.Id } catch { } " />
    <div class="form-group">
        <label>Nome</label>
        <input asp-for="Nome" type="text" class="form-control" value="@try { @ViewBag.Vendedor.Nome } catch { } " />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Email</label>
        <input asp-for="Email" type="text" class="form-control" value="@try { @ViewBag.Vendedor.Email } catch { } " />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Lista de Vendedor</button>

<script>
    function Voltar() {
        window.location.href = '../../Vendedor/Index';
    }
</script>

Views/Vendedor/Excluir.cshtml
<h2>Excluir Vendedor</h2>

<h3>Deseja realmente excluir o cliente selecionado?</h3>
<br />
<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>
    function Sim()
    {
        window.location.href = '../../Vendedor/ExcluirVendedor/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao()
    {
        window.location.href = '../../Vendedor/Index';
    }

</script>

Views/Vendedor/ExcluirVendedor.cshtml
<h2>Vendedor excluido com sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">OK</button>

<script>
    function Voltar()
    {
        window.location.href = '../../Vendedor/Index';
    }
</script>

Views/Vendedor/Index.cshtml
<h3>Lista de Vendedores</h3>

<table class="table table-bordered">

    <thead>
        <tr>
            <td>#</td>
            <td>#</td>
            <td>Id</td>
            <td>Nome</td>
            <td>Email</td>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var item in (List<VendedorModel>)ViewBag.ListaVendedores)
            {
                <tr>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
                    <td>@item.Id</td>
                    <td>@item.Nome</td>
                    <td>@item.Email</td>
                </tr>

            }
        }
    </tbody>

</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar</button>

<script>
    function Cadastrar() {
        window.location.href = "../Vendedor/Cadastro";
    }

    function Editar(id) {
        window.location.href = "../Vendedor/Cadastro/" + id;
    }

    function Excluir(id) {
        window.location.href = "../Vendedor/Excluir/" + id;
    }
</script>

<br /><br />
<button class="btn btn-block btn-primary" type="button" onclick="Voltar()">Retornar para Menu</button>

<script>
    function Voltar() {
        window.location.href = "../Home/Menu"
    }
</script>